language: python
python:
  - "3.6"
cache: pip

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
  - pip install nose

services:
   - postgresql

# command to run tests
script:
  - nosetests -v --with-coverage --cover-package=api
# command to run tests

after_success:
- coveralls