language: python
python:
  - "3.6"
cache: pip
# command to install dependencies
:
  - chmod +x ./cc-test-reporter
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
  - pip install nose
  
# command to run tests
script:
  - nosetests -v --with-coverage --cover-package=api

after_success:
- coveralls
